BugFix for LuaLaTeX and LuaTeX Tool Chain
It seems that the LuaLaTeX and LuaTeX tool chains have problems with
`eps` figures on vanilla TeXLive installations. The reason probably is
that they Lua*TeX converts these figures to `pdf` using some util which
isn't there.

Thus Travis CI fails with

test.junit.org.optimizationBenchmarking.utils.tools.impl.latex.LaTeXTest

testCanBuildWithEPS(test.junit.org.optimizationBenchmarking.utils.tools.impl.latex.LaTeXTest)
Time elapsed: 1.098 sec  <<< ERROR!

java.lang.RuntimeException: Example LaTeX file generation and
compilation failed with job [LuaTeX used as LuaLaTeX(/usr/bin/luatex
--output-format=pdf --progname=lualatex --halt-on-error)]+ --> [] in
/tmp/6560481924520301266

in build

https://travis-ci.org/optimizationBenchmarking/optimizationBenchmarking/jobs/70878811

This would mean we should put these tool chains to the end of the choice
list. However, they also have beneficial features, such as being able
to dynamically allocate more memory if necessary.

I therefore develop the following solutions: Lua*TeX is the default
tool chain for any of the graphics format that it supports, accept for
`eps`. For `eps`, we put it to the end of the list and only use it if
all other possible tool chains (such as plain LaTeX) cannot be detected.